#
# This source file is part of the SpeziSensorKit open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  package_ios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziSensorKit
      resultBundle: SpeziSensorKit-iOS.xcresult
      artifactname: SpeziSensorKit-iOS.xcresult
  uitests:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [package_ios, uitests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziSensorKit-iOS.xcresult TestApp-iOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
